env: dev

server:
  port: 8080

db:
  driver: mysql
  host: localhost
  port: 33306
  database: go_project_template
  username: root
  password: v6SxhWHyZC7S
  max_idle_conns: 10
  max_open_conns: 100

redis:
  host: localhost
  port: 36379
  password: 


kafka:
  addrs:
    - localhost:9092

log:
  level: info
  path: "logs"
  maxSize: 10
  maxBackups: 30
  maxAge: 7
  compress: true
  localTime: true
  console: true